"""Config flow for SmartIR Native."""

from typing import Any

import voluptuous as vol

from homeassistant.components.infrared import (
    DOMAIN as INFRARED_DOMAIN,
    async_get_emitters,
    async_get_receivers,
)
from homeassistant.config_entries import (
    ConfigEntry,
    ConfigFlow,
    ConfigFlowResult,
    OptionsFlowWithReload,
)
from homeassistant.core import callback
from homeassistant.helpers.selector import (
    EntitySelector,
    EntitySelectorConfig,
    TextSelector,
    TextSelectorConfig,
    TextSelectorType,
)

from .const import (
    CONF_INFRARED_ENTITY_ID,
    CONF_INFRARED_RECEIVER_ENTITY_ID,
    CONF_NAME,
    CONF_PROFILE_CODE,
    DOMAIN,
)
from .profile import InvalidProfile, decode_profile_code, profile_name


def _device_schema(
    name: str,
    emitters: list[str],
    receivers: list[str],
    *,
    emitter: str | None = None,
    receiver: str | None = None,
) -> vol.Schema:
    """Build the shared device form for setup and reconfiguration."""
    emitter_marker = (
        vol.Required(CONF_INFRARED_ENTITY_ID, default=emitter)
        if emitter
        else vol.Required(CONF_INFRARED_ENTITY_ID)
    )
    schema_fields: dict[vol.Marker, Any] = {
        vol.Required(CONF_NAME, default=name): TextSelector(
            TextSelectorConfig(type=TextSelectorType.TEXT)
        ),
        emitter_marker: EntitySelector(
            EntitySelectorConfig(
                domain=INFRARED_DOMAIN,
                include_entities=emitters,
            )
        ),
    }
    if receivers:
        receiver_marker = (
            vol.Optional(CONF_INFRARED_RECEIVER_ENTITY_ID, default=receiver)
            if receiver
            else vol.Optional(CONF_INFRARED_RECEIVER_ENTITY_ID)
        )
        schema_fields[receiver_marker] = EntitySelector(
            EntitySelectorConfig(
                domain=INFRARED_DOMAIN,
                include_entities=receivers,
            )
        )
    return vol.Schema(schema_fields)


class SmartIrNativeConfigFlow(ConfigFlow, domain=DOMAIN):
    """Add climate entities from portable SmartIR profile codes."""

    VERSION = 1

    def __init__(self) -> None:
        """Initialize the flow."""
        self._profile_code: str | None = None
        self._suggested_name: str | None = None

    @staticmethod
    @callback
    def async_get_options_flow(
        config_entry: ConfigEntry,
    ) -> "SmartIrNativeOptionsFlow":
        """Return the editable emitter and receiver options flow."""
        return SmartIrNativeOptionsFlow()

    async def async_step_user(
        self, user_input: dict[str, Any] | None = None
    ) -> ConfigFlowResult:
        """Accept and validate a profile code generated by the website."""
        if not async_get_emitters(self.hass):
            return self.async_abort(reason="no_infrared_emitters")

        errors: dict[str, str] = {}
        if user_input is not None:
            try:
                device = decode_profile_code(user_input[CONF_PROFILE_CODE])
            except InvalidProfile:
                errors[CONF_PROFILE_CODE] = "invalid_profile"
            else:
                self._profile_code = "".join(
                    user_input[CONF_PROFILE_CODE].split()
                )
                self._suggested_name = profile_name(device)
                return await self.async_step_device()

        schema = vol.Schema(
            {
                vol.Required(CONF_PROFILE_CODE): TextSelector(
                    TextSelectorConfig(
                        multiline=True,
                        type=TextSelectorType.TEXT,
                    )
                )
            }
        )
        return self.async_show_form(
            step_id="user",
            data_schema=schema,
            errors=errors,
        )

    async def async_step_device(
        self, user_input: dict[str, Any] | None = None
    ) -> ConfigFlowResult:
        """Choose an emitter and name for the new climate entity."""
        if self._profile_code is None or self._suggested_name is None:
            return self.async_abort(reason="invalid_profile")

        emitters = async_get_emitters(self.hass)
        if not emitters:
            return self.async_abort(reason="no_infrared_emitters")

        if user_input is not None:
            entry_data = {
                CONF_NAME: user_input[CONF_NAME],
                CONF_INFRARED_ENTITY_ID: user_input[CONF_INFRARED_ENTITY_ID],
                CONF_PROFILE_CODE: self._profile_code,
            }
            if receiver := user_input.get(CONF_INFRARED_RECEIVER_ENTITY_ID):
                entry_data[CONF_INFRARED_RECEIVER_ENTITY_ID] = receiver
            return self.async_create_entry(
                title=user_input[CONF_NAME],
                data=entry_data,
            )

        schema = _device_schema(
            self._suggested_name,
            emitters,
            async_get_receivers(self.hass),
        )
        return self.async_show_form(step_id="device", data_schema=schema)

    async def async_step_reconfigure(
        self, user_input: dict[str, Any] | None = None
    ) -> ConfigFlowResult:
        """Change the emitter, optional receiver, or entity name."""
        entry = self._get_reconfigure_entry()
        emitters = async_get_emitters(self.hass)
        current_emitter = entry.data[CONF_INFRARED_ENTITY_ID]
        if current_emitter not in emitters:
            emitters.append(current_emitter)
        receivers = async_get_receivers(self.hass)
        current_receiver = entry.data.get(CONF_INFRARED_RECEIVER_ENTITY_ID)
        if current_receiver and current_receiver not in receivers:
            receivers.append(current_receiver)

        if user_input is not None:
            updated_data = {
                **entry.data,
                CONF_NAME: user_input[CONF_NAME],
                CONF_INFRARED_ENTITY_ID: user_input[CONF_INFRARED_ENTITY_ID],
                CONF_INFRARED_RECEIVER_ENTITY_ID: user_input.get(
                    CONF_INFRARED_RECEIVER_ENTITY_ID
                ),
            }
            updated_options = {
                **entry.options,
                CONF_INFRARED_ENTITY_ID: user_input[CONF_INFRARED_ENTITY_ID],
                CONF_INFRARED_RECEIVER_ENTITY_ID: user_input.get(
                    CONF_INFRARED_RECEIVER_ENTITY_ID
                ),
            }
            return self.async_update_reload_and_abort(
                entry,
                title=user_input[CONF_NAME],
                data=updated_data,
                options=updated_options,
            )

        return self.async_show_form(
            step_id="reconfigure",
            data_schema=_device_schema(
                entry.data[CONF_NAME],
                emitters,
                receivers,
                emitter=current_emitter,
                receiver=current_receiver,
            ),
        )


class SmartIrNativeOptionsFlow(OptionsFlowWithReload):
    """Edit the Infrared emitter and optional receiver."""

    async def async_step_init(
        self, user_input: dict[str, Any] | None = None
    ) -> ConfigFlowResult:
        """Show and save editable Infrared entities."""
        entry = self.config_entry
        current_emitter = entry.options.get(
            CONF_INFRARED_ENTITY_ID,
            entry.data[CONF_INFRARED_ENTITY_ID],
        )
        current_receiver = entry.options.get(
            CONF_INFRARED_RECEIVER_ENTITY_ID,
            entry.data.get(CONF_INFRARED_RECEIVER_ENTITY_ID),
        )

        if user_input is not None:
            return self.async_create_entry(
                data={
                    CONF_INFRARED_ENTITY_ID: user_input[CONF_INFRARED_ENTITY_ID],
                    CONF_INFRARED_RECEIVER_ENTITY_ID: user_input.get(
                        CONF_INFRARED_RECEIVER_ENTITY_ID
                    ),
                }
            )

        emitters = async_get_emitters(self.hass)
        if current_emitter not in emitters:
            emitters.append(current_emitter)
        receivers = async_get_receivers(self.hass)
        if current_receiver and current_receiver not in receivers:
            receivers.append(current_receiver)

        emitter_marker = vol.Required(
            CONF_INFRARED_ENTITY_ID,
            default=current_emitter,
        )
        schema_fields: dict[vol.Marker, Any] = {
            emitter_marker: EntitySelector(
                EntitySelectorConfig(
                    domain=INFRARED_DOMAIN,
                    include_entities=emitters,
                )
            )
        }
        if receivers:
            receiver_marker = (
                vol.Optional(
                    CONF_INFRARED_RECEIVER_ENTITY_ID,
                    default=current_receiver,
                )
                if current_receiver
                else vol.Optional(CONF_INFRARED_RECEIVER_ENTITY_ID)
            )
            schema_fields[receiver_marker] = EntitySelector(
                EntitySelectorConfig(
                    domain=INFRARED_DOMAIN,
                    include_entities=receivers,
                )
            )
        return self.async_show_form(
            step_id="init",
            data_schema=vol.Schema(schema_fields),
        )
