"""Constants for SmartIR Native."""

DOMAIN = "smartir_native"
NAME = "SmartIR Native"

CONF_INFRARED_ENTITY_ID = "infrared_entity_id"
CONF_INFRARED_RECEIVER_ENTITY_ID = "infrared_receiver_entity_id"
CONF_CARRIER_FREQUENCY = "carrier_frequency"
CONF_TIMING_SCALE = "timing_scale"
CONF_NAME = "name"
CONF_PROFILE_CODE = "profile_code"

DEFAULT_CARRIER_FREQUENCY = 38_000
DEFAULT_TIMING_SCALE = 100
MIN_CARRIER_FREQUENCY = 20_000
MAX_CARRIER_FREQUENCY = 60_000
MIN_TIMING_SCALE = 80
MAX_TIMING_SCALE = 120
